### ISSUE TITLE
Build fails: Generated xed-reg-enum.h misses a number of enum entries

### ISSUE THREAD

**Issue by hansfbaier** [jakobbotsch/xed.NET#1]
When I execute the build instructions in the readme, the xed-reg-enum.h
generated misses quite a number of items referenced in Enums.h, including:

`        Dr8 = XED_REG_DR8,
        Dr9 = XED_REG_DR9,
        Dr10 = XED_REG_DR10,
        Dr11 = XED_REG_DR11,
        Dr12 = XED_REG_DR12,
        Dr13 = XED_REG_DR13,
        Dr14 = XED_REG_DR14,
        Dr15 = XED_REG_DR15,`

But DR0-7 are included in the enum file. This makes no difference whether I generate for 64 bit or 32 bit architecture.

If I look at xed/datafiles/xed-reg-tables.txt, I get:
`
xed_reg_enum_t DR_R()::
REXR=0 REG=0x0  | OUTREG=XED_REG_DR0
REXR=0 REG=0x1  | OUTREG=XED_REG_DR1
REXR=0 REG=0x2  | OUTREG=XED_REG_DR2
REXR=0 REG=0x3  | OUTREG=XED_REG_DR3
REXR=0 REG=0x4  | OUTREG=XED_REG_DR4
REXR=0 REG=0x5  | OUTREG=XED_REG_DR5
REXR=0 REG=0x6  | OUTREG=XED_REG_DR6
REXR=0 REG=0x7  | OUTREG=XED_REG_DR7
REXR=1 REG=0x0  | OUTREG=XED_REG_ERROR enc
REXR=1 REG=0x1  | OUTREG=XED_REG_ERROR
REXR=1 REG=0x2  | OUTREG=XED_REG_ERROR
REXR=1 REG=0x3  | OUTREG=XED_REG_ERROR
REXR=1 REG=0x4  | OUTREG=XED_REG_ERROR
REXR=1 REG=0x5  | OUTREG=XED_REG_ERROR
REXR=1 REG=0x6  | OUTREG=XED_REG_ERROR
REXR=1 REG=0x7  | OUTREG=XED_REG_ERROR
`
So only DR0-7 are defined here. When I create a branch from revision before DR8-15 were
removed, I get other enums missing.

Which revision of xed did you base your work on?

**Comment by hansfbaier** [comment]
I found a revision which works: `8922c2d21ec7110f0ccf33bbdad146d93222918b`.

Would be nice if you included xed with the right revision as a git submodule, so other users would not need to go through the same hassle.!

**Comment by jakobbotsch** [comment]
Sorry I missed this. But I can see you found the revision. I will add the hash to the README.
Thanks for letting me know!

**Comment by jakobbotsch** [comment]
Done in 90b11f2.
